version: '3'

services:
  monner-service:
    build: ./DagensMonnerWithEntityFramework
    image: monner-service-image
    container_name: monner-service
    depends_on:
      - monner-db
    ports:
      - "80:80"
  
  monner-db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: monner-db
    ports: 
      - "1433:1433"
    environment:
      SA_PASSWORD: "ThisIsPassword"
      ACCEPT_EULA: "Y"
    volumes:
    - ./Data:/var/opt/mssql/data
  
